# Example configuration file for  interpolation
# from Erkal et al. 2016 []
stream:
  stream_name: &stream_name "atlas"
  filename : &filename ./data/patrick_2022_splines.csv
  nstars: 5.0e+3

  linear_density:
    type: FileLinearDensityCubicSplineInterpolation
    filename: *filename
    stream_name: *stream_name

  track:
    center:
      type: FileCubicSplineInterpolation
      filename: *filename
      stream_name: *stream_name
      spline_type: center
    spread:
      type: FileCubicSplineInterpolation
      filename: *filename
      stream_name: *stream_name
      spline_type: spread
    sampler: Gaussian

background:
  nstars : 1.0e+5

  density:
    type: Uniform
    xmin: -15.0
    xmax: +10.0

  track:
    center:
      type: Constant
      value: 0.0
    spread:
      type: Constant
      value: 4.0
    sampler: Uniform
