- DiscoveryRefs: Odenkirchen2001
  ID: ''
  Imp: st
  InfoFlags: '1111'
  L_Ref: '--------'
  Lv_stream: 0.0
  Name: Pal5
  Notes: '-'
  'On': false
  TrackName: Pal5-I24
  TrackRefs: ibata2024
  TrackRefsLatex: Ibata2024
  dec_f: 9.279576254116762
  dec_mid: 1.7675485937650193
  dec_o: -10.644267714585839
  dec_pole: 56.28496339844274
  distance_f: 1.0
  distance_mid: 0.9999999999999998
  distance_o: 1.0000000000000016
  from-Members: 1
  has_D: 1
  has_empirical_track: 1
  has_pm: 1
  has_vrad: 1
  length: 32.59631131370912
  ra_f: 245.89465019770668
  ra_mid: 231.7956214155731
  ra_o: 220.98008280733634
  ra_pole: 139.15079555577654
  total_v_sigma: -1.0
  total_v_sigma_Ref: from-Members
  width_comment: apparent
  width_phi2: 0.3
  width_phi2_Ref: from-Members
  width_pm_phi1_cosphi2: 0.15
  width_pm_phi1_cosphi2_Ref: from-Members
  width_pm_phi2: 0.16
  width_pm_phi2_Ref: from-Members
- DiscoveryRefs: Odenkirchen2001
  ID: ''
  Imp: st
  InfoFlags: '1111'
  L_Ref: '--------'
  Lv_stream: 0.0
  Name: Pal5
  Notes: GC
  'On': false
  TrackName: Pal5-I21
  TrackRefs: ibata2021
  TrackRefsLatex: Ibata2021
  dec_f: 6.085955568755689
  dec_mid: 1.0412800052684168
  dec_o: -7.4834761448983205
  dec_pole: 55.41679995077607
  distance_f: 20.373165066141414
  distance_mid: 22.358774187210763
  distance_o: 17.813346538952818
  from-Members: 1
  has_D: 1
  has_empirical_track: 1
  has_pm: 1
  has_vrad: 1
  length: 22.34466136021861
  ra_f: 240.1659773257782
  ra_mid: 230.43181872061908
  ra_o: 223.09446153773624
  ra_pole: 138.92980873362688
  total_v_sigma: -1.0
  total_v_sigma_Ref: from-Members
  width_comment: apparent
  width_phi2: 0.41
  width_phi2_Ref: from-Members
  width_pm_phi1_cosphi2: 0.48
  width_pm_phi1_cosphi2_Ref: from-Members
  width_pm_phi2: 0.27
  width_pm_phi2_Ref: from-Members
- DiscoveryRefs: Odenkirchen2001
  ID: 117
  Imp: st
  InfoFlags: '1110'
  L_Ref: '--------'
  Lv_stream: 0.0
  Name: Pal5
  Notes: GC
  'On': true
  TrackName: Pal5-PW19
  TrackRefs: pricewhelan2019
  TrackRefsLatex: PriceWhelan2019_pal5,Bonaca2020
  dec_f: -4.800515070822196
  dec_mid: -0.10579354904551765
  dec_o: 6.883094642923846
  dec_pole: -56.48977919831249
  distance_f: 19.08823393707333
  distance_mid: 20.537973603990853
  distance_o: 22.023408282052685
  from-Members: 1
  has_D: 1
  has_empirical_track: 1
  has_pm: 1
  has_vrad: 0
  length: 21.389020171273007
  ra_f: 224.65738998670705
  ra_mid: 229.00594480229785
  ra_o: 242.09382462115624
  ra_pole: 319.20527302462244
  total_v_sigma: -9.0
  total_v_sigma_Ref: from-Members
  width_comment: apparent
  width_phi2: -9.0
  width_phi2_Ref: from-Members
  width_pm_phi1_cosphi2: -9.0
  width_pm_phi1_cosphi2_Ref: from-Members
  width_pm_phi2: -9.0
  width_pm_phi2_Ref: from-Members
- DiscoveryRefs: Odenkirchen2001
  ID: ''
  Imp: st
  InfoFlags: '1000'
  L_Ref: '--------'
  Lv_stream: 0.0
  Name: Pal5
  Notes: GC
  'On': false
  TrackName: Pal5-S20
  TrackRefs: starkman2020
  TrackRefsLatex: Starkman2020
  dec_f: -11.980544528948892
  dec_mid: -0.21075184132657168
  dec_o: 5.230912164723605
  dec_pole: -48.31
  distance_f: 22.50000000000001
  distance_mid: 22.499999999999996
  distance_o: 22.50000000000001
  from-Members: 0
  has_D: 0
  has_empirical_track: 1
  has_pm: 0
  has_vrad: 0
  length: 27.229987488928266
  ra_f: 220.62789417340835
  ra_mid: 229.01315826015508
  ra_o: 240.3121812410191
  ra_pole: 319.27
  total_v_sigma: -9.0
  total_v_sigma_Ref: '-----------'
  width_comment: apparent
  width_phi2: 0.3
  width_phi2_Ref: Riley2020
  width_pm_phi1_cosphi2: -9.0
  width_pm_phi1_cosphi2_Ref: '-----------'
  width_pm_phi2: -9.0
  width_pm_phi2_Ref: '------------'
- cluster: Pal5
  dec: -0.124
  dec_unit: deg
  distance: 22.9
  distance_unit: kpc
  frame: icrs
  pm_dec: -2.257
  pm_dec_unit: mas/yr
  pm_ra_cosdec: -2.296
  pm_ra_cosdec_unit: mas/yr
  ra: 229
  ra_unit: deg
  radial_velocity: -58.7
  radial_velocity_unit: km/s
