- DiscoveryRefs: Belokurov2006_5466,Grillmair2006_5466
  ID: 75
  Imp: st
  InfoFlags: '1110'
  L_Ref: '--------'
  Lv_stream: 0.0
  Name: NGC5466
  Notes: GC
  'On': true
  TrackName: NGC5466-J21
  TrackRefs: jensen2021
  TrackRefsLatex: Jensen2021
  dec_f: 21.77842502494974
  dec_mid: 28.512738433248
  dec_o: 35.496395182058286
  dec_pole: 50.756136206579995
  distance_f: 14.322757334368177
  distance_mid: 16.738498134386443
  distance_o: 26.80783989886806
  from-Members: 1
  has_D: 1
  has_empirical_track: 1
  has_pm: 1
  has_vrad: 0
  length: 30.899288281936506
  ra_f: 224.6121312321029
  ra_mid: 211.34098698504917
  ra_o: 192.83628232331967
  ra_pole: 343.1410548910589
  total_v_sigma: -1.0
  total_v_sigma_Ref: from-Members
  width_comment: apparent
  width_phi2: 1.2
  width_phi2_Ref: from-Members
  width_pm_phi1_cosphi2: 0.24
  width_pm_phi1_cosphi2_Ref: from-Members
  width_pm_phi2: 0.27
  width_pm_phi2_Ref: from-Members
- cluster: NGC5466-J21
  dec: 28.53
  dec_unit: deg
  distance: 16.0
  distance_unit: kpc
  frame: icrs
  pm_dec: -0.79
  pm_dec_unit: mas/yr
  pm_ra_cosdec: -5.41
  pm_ra_cosdec_unit: mas/yr
  ra: 211.36
  ra_unit: deg
  radial_velocity: 106.93
  radial_velocity_unit: km/s
