# Example configuration file for Pal 5 interpolation
# from Erkal et al. 2016 []
stream:
  filename : &filename ./data/hall_2024_Pal5_input.csv
  nstars: 1.15e+5
   
  density:
    type: FileInterpolation
    filename : *filename
    columns : [phi1, nstars]
   
  track:
    center:
      type: FileInterpolation
      filename: *filename
      columns: [phi1, phi2]
    spread:
      type: FileInterpolation
      filename: *filename
      columns: [phi1, width]
    sampler: Gaussian
  
  isochrone:
    name: Bressan2012
    survey: lsst
    age: 12.0
    z: 0.0006
    band_1 : g
    band_2 : r
    band_1_detection : True
  
  distance_modulus:
    center: 
      type: Line
      slope: 0.1
      intercept: 16.5
    spread:
      type: Constant
      value: 0.0001 
    sampler: Uniform

   
background:
  nstars : 1.0e+5

  density:
    type: Uniform
    xmin: -10.0
    xmax: +18.0

  track:
    center:
      type: Constant
      value: 0.0
    spread:
      type: Constant
      value: 4.0
    sampler: Uniform