background:
  density:
    type: Uniform
    xmax: 18.0
    xmin: -10.0
  nstars: 100000.0
  track:
    center:
      type: Constant
      value: 0.0
    sampler: Uniform
    spread:
      type: Constant
      value: 4.0
stream:
  density:
    columns:
    - phi1
    - nstars
    filename: ./data/erkal_2016_pal_5_input.csv
    type: FileInterpolation
  distance_modulus:
    center:
      intercept: 16.5
      slope: 0.1
      type: Line
    sampler: Uniform
    spread:
      type: Constant
      value: 0.0001
  filename: ./data/erkal_2016_pal_5_input.csv
  isochrone:
    age: 12.0
    band_1: g
    band_1_detection: true
    band_2: r
    name: Bressan2012
    z: 0.0006
  nstars: 115000.0
  track:
    center:
      columns:
      - phi1
      - phi2
      filename: ./data/erkal_2016_pal_5_input.csv
      type: FileInterpolation
    sampler: Gaussian
    spread:
      columns:
      - phi1
      - width
      filename: ./data/erkal_2016_pal_5_input.csv
      type: FileInterpolation
